apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alerting-rules
data:
  loki-alerting-rules.yaml: |-
    groups:
      - name: JDBCAlert
        rules:
          - alert: JDBCAlert
            expr: |
              count_over_time({namespace="ng-dev-flux"} |~ "(?i)Failed to validate connection org.postgresql.jdbc.PgConnection" [1000m]) > 0
            for: 30s
            labels:
              severity: medium
              job: jdbc
            annotations:
              summary: Connection validation for jdbc pg-connection failed
    groups:
      - name: BEVMO prod rules
        rules:
          - alert: IPL Failed - BEVMO prod
            expr: |
              count_over_time({namespace="bevmo-dev-flux"}  |~ ".*IPL_FAIL.*" [1m] ) > 0
            for: 30s
            labels:
                severity: medium
                error: IPL_FAIL
            annotations:
                summary: IPL_FAIL in bevmo prod           