annotations:
  artifacthub.io/license: AGPL-3.0-only
  artifacthub.io/links: |
    - name: dependencie Chart Source
      url: https://charts.min.io/
    - name: Upstream Project
      url: https://grafana.github.io/helm-charts
apiVersion: v2
name: loki
description: Helm chart for Grafana Loki in simple, scalable mode
type: application
appVersion: 2.9.3
version: 5.41.25
home: https://grafana.github.io/helm-charts
sources:
  - https://github.com/grafana/loki
  - https://grafana.com/oss/loki/
  - https://grafana.com/docs/loki/latest/
  - https://charts.min.io/
  - https://grafana.github.io/helm-charts
icon: https://grafana.com/docs/loki/latest/logo_and_name.png
dependencies:
  - name: minio
    alias: minio
    version: 4.0.15
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: grafana-agent-operator
    alias: grafana-agent-operator
    version: 0.2.16
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.selfMonitoring.grafanaAgent.installOperator
maintainers:
  - name: trevorwhitney
  - name: jeschkies
